version: "3.9"

services:
  # --- TU PORTFOLIO (WEB PERSONAL) ---
  # Asegúrate de que la carpeta se llama 'portfolio-cv' o cámbialo abajo
  portfolio-personal:
    build: ./portfolio-cv  # Asegúrate de que este nombre coincide con tu carpeta en VS Code
    restart: unless-stopped
    expose:
      - "80"
    networks:
      - gestor-web_default

  # --- LA INTRANET (BASE DE DATOS) ---
  mongo:
    image: mongo:7
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M
    volumes:
      - mongo_data:/data/db
    networks:
      - intranet

  # --- LA INTRANET (BACKEND) ---
  backend:
    build: ./server
    restart: unless-stopped
    environment:
      NODE_ENV: production
      MONGO_URL: mongodb://mongo:27017/cesar_intranet
      JWT_SECRET: ${JWT_SECRET:-change_me}
      UPLOADS_DIR: /app/uploads
    volumes:
      - uploads_data:/app/uploads
    depends_on:
      - mongo
    expose:
      - "4000"
    networks:
      - intranet
      - gestor-web_default

  # --- LA INTRANET (FRONTEND) ---
  intranet-frontend:
    build: ./client
    restart: unless-stopped
    depends_on:
      - backend
    expose:
      - "80"
    networks:
      - intranet
      - gestor-web_default

volumes:
  mongo_data:
  uploads_data:

networks:
  intranet:
  gestor-web_default:
    external: true